### ISSUE TITLE
Table Headers are Always Left Aligned

### ISSUE THREAD

**Issue by ChampionAsh5357** [MinecraftForge/Documentation#431]
Table headers are always left aligned. This seems to be as a result of a configuration in [Web](https://github.com/MinecraftForge/Web/blob/master/sass/_reboot.scss#L289-L292) which was not properly handled for GitHub markdown.

![Left Aligned Table](https://imgur.com/pkb6UzK.png)

This can be remedied using attribute selectors on the CSS headers to match the alignment of the `td`:

```css
th[align="center"] {
    text-align: center;
}

th[align="left"] {
    text-align: left;
}

th[align="right"] {
    text-align: right;
}
```
